// Generated by scripts/gen-gateway-inventory.ts — do not edit by hand.
// Source: hermes-agent@4da7b9ee029c6ece2eb7992fc27dbcd086982c84 tui_gateway/server.py
// RPC methods: 135; events: 54

export const GATEWAY_INVENTORY = {
  "provenance": {
    "sourceRevision": "4da7b9ee029c6ece2eb7992fc27dbcd086982c84",
    "sourceLabel": "hermes-agent@4da7b9ee029c6ece2eb7992fc27dbcd086982c84",
    "extractor": "scripts/gen-gateway-inventory.ts",
    "boundary": "static Python AST over explicit HERMES_AGENT_ROOT; no imports, gateway startup, HERMES_HOME reads, or producer execution",
    "inputs": [
      "tools/__init__.py",
      "tools/ansi_strip.py",
      "tools/approval.py",
      "tools/async_delegation.py",
      "tools/binary_extensions.py",
      "tools/blueprints.py",
      "tools/browser_camofox.py",
      "tools/browser_camofox_state.py",
      "tools/browser_cdp_tool.py",
      "tools/browser_dialog_tool.py",
      "tools/browser_supervisor.py",
      "tools/browser_tool.py",
      "tools/budget_config.py",
      "tools/checkpoint_manager.py",
      "tools/clarify_gateway.py",
      "tools/clarify_tool.py",
      "tools/close_terminal_tool.py",
      "tools/code_execution_tool.py",
      "tools/computer_use_tool.py",
      "tools/credential_files.py",
      "tools/cronjob_tools.py",
      "tools/daemon_pool.py",
      "tools/debug_helpers.py",
      "tools/delegate_tool.py",
      "tools/delegation_live_log.py",
      "tools/desktop_ui.py",
      "tools/discord_tool.py",
      "tools/env_passthrough.py",
      "tools/env_probe.py",
      "tools/fal_common.py",
      "tools/feishu_doc_tool.py",
      "tools/feishu_drive_tool.py",
      "tools/file_operations.py",
      "tools/file_state.py",
      "tools/file_tools.py",
      "tools/focus_pane_tool.py",
      "tools/fuzzy_match.py",
      "tools/homeassistant_tool.py",
      "tools/hook_output_spill.py",
      "tools/image_generation_tool.py",
      "tools/image_source.py",
      "tools/interrupt.py",
      "tools/kanban_tools.py",
      "tools/lazy_deps.py",
      "tools/managed_tool_gateway.py",
      "tools/mcp_dashboard_oauth.py",
      "tools/mcp_oauth.py",
      "tools/mcp_oauth_manager.py",
      "tools/mcp_stdio_watchdog.py",
      "tools/mcp_tool.py",
      "tools/memory_tool.py",
      "tools/microsoft_graph_auth.py",
      "tools/microsoft_graph_client.py",
      "tools/neutts_synth.py",
      "tools/open_preview_tool.py",
      "tools/openrouter_client.py",
      "tools/osv_check.py",
      "tools/patch_parser.py",
      "tools/path_security.py",
      "tools/process_registry.py",
      "tools/project_tools.py",
      "tools/read_extract.py",
      "tools/read_terminal_tool.py",
      "tools/registry.py",
      "tools/schema_sanitizer.py",
      "tools/send_message_tool.py",
      "tools/session_search_tool.py",
      "tools/skill_manager_tool.py",
      "tools/skill_provenance.py",
      "tools/skill_usage.py",
      "tools/skills_ast_audit.py",
      "tools/skills_guard.py",
      "tools/skills_hub.py",
      "tools/skills_sync.py",
      "tools/skills_tool.py",
      "tools/slash_confirm.py",
      "tools/terminal_tool.py",
      "tools/thread_context.py",
      "tools/threat_patterns.py",
      "tools/tirith_security.py",
      "tools/todo_tool.py",
      "tools/tool_backend_helpers.py",
      "tools/tool_output_limits.py",
      "tools/tool_result_storage.py",
      "tools/tool_search.py",
      "tools/transcription_tools.py",
      "tools/tts_streaming.py",
      "tools/tts_tool.py",
      "tools/url_safety.py",
      "tools/video_generation_tool.py",
      "tools/vision_tools.py",
      "tools/voice_mode.py",
      "tools/web_tools.py",
      "tools/website_policy.py",
      "tools/working_diff.py",
      "tools/write_approval.py",
      "tools/x_search_tool.py",
      "tools/xai_http.py",
      "tools/xai_video_tools.py",
      "tools/yuanbao_tools.py",
      "tui_gateway/entry.py",
      "tui_gateway/server.py",
      "tui_gateway/ws.py"
    ]
  },
  "rpc": {
    "methods": [
      "agents.list",
      "approval.respond",
      "billing.auto_reload",
      "billing.charge",
      "billing.charge_status",
      "billing.state",
      "billing.step_up",
      "browser.manage",
      "clarify.respond",
      "cli.exec",
      "clipboard.paste",
      "command.dispatch",
      "command.resolve",
      "commands.catalog",
      "complete.path",
      "complete.slash",
      "config.get",
      "config.set",
      "config.show",
      "cron.manage",
      "delegation.pause",
      "delegation.status",
      "file.attach",
      "handoff.fail",
      "handoff.request",
      "handoff.state",
      "image.attach",
      "image.attach_bytes",
      "image.detach",
      "input.detect_drop",
      "insights.get",
      "learning.delete",
      "learning.detail",
      "learning.edit",
      "learning.frames",
      "llm.oneshot",
      "model.disconnect",
      "model.options",
      "model.save_key",
      "paste.collapse",
      "pdf.attach",
      "pet.cancel",
      "pet.cells",
      "pet.disable",
      "pet.export",
      "pet.gallery",
      "pet.generate",
      "pet.generate.status",
      "pet.hatch",
      "pet.info",
      "pet.info.meta",
      "pet.remove",
      "pet.rename",
      "pet.scale",
      "pet.select",
      "pet.thumb",
      "plugins.list",
      "plugins.manage",
      "preview.restart",
      "process.kill",
      "process.list",
      "process.stop",
      "project.facts",
      "projects.add_folder",
      "projects.archive",
      "projects.create",
      "projects.delete",
      "projects.discover_repos",
      "projects.for_cwd",
      "projects.get",
      "projects.list",
      "projects.project_sessions",
      "projects.record_repos",
      "projects.remove_folder",
      "projects.set_active",
      "projects.set_primary",
      "projects.tree",
      "projects.update",
      "prompt.background",
      "prompt.submit",
      "reload.env",
      "reload.mcp",
      "rollback.diff",
      "rollback.list",
      "rollback.restore",
      "secret.respond",
      "session.activate",
      "session.active_list",
      "session.branch",
      "session.close",
      "session.compress",
      "session.context_breakdown",
      "session.create",
      "session.cwd.set",
      "session.delete",
      "session.history",
      "session.interrupt",
      "session.list",
      "session.most_recent",
      "session.redirect",
      "session.resume",
      "session.save",
      "session.status",
      "session.steer",
      "session.title",
      "session.undo",
      "session.usage",
      "setup.runtime_check",
      "setup.status",
      "shell.exec",
      "skills.manage",
      "skills.reload",
      "slash.exec",
      "spawn_tree.list",
      "spawn_tree.load",
      "spawn_tree.save",
      "subagent.interrupt",
      "subscription.change",
      "subscription.preview",
      "subscription.resume",
      "subscription.state",
      "subscription.upgrade",
      "sudo.respond",
      "system.battery",
      "terminal.read.respond",
      "terminal.resize",
      "tools.configure",
      "tools.list",
      "tools.show",
      "toolsets.list",
      "usage.bars",
      "verification.status",
      "voice.record",
      "voice.toggle",
      "voice.tts"
    ],
    "sources": [
      {
        "kind": "decorator",
        "line": 18312,
        "name": "agents.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13215,
        "name": "approval.respond",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9869,
        "name": "billing.auto_reload",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9814,
        "name": "billing.charge",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9840,
        "name": "billing.charge_status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9535,
        "name": "billing.state",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9891,
        "name": "billing.step_up",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17901,
        "name": "browser.manage",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13187,
        "name": "clarify.respond",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15277,
        "name": "cli.exec",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12394,
        "name": "clipboard.paste",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15348,
        "name": "command.dispatch",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15318,
        "name": "command.resolve",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15155,
        "name": "commands.catalog",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 16211,
        "name": "complete.path",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 16479,
        "name": "complete.slash",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14526,
        "name": "config.get",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13240,
        "name": "config.set",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18100,
        "name": "config.show",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18336,
        "name": "cron.manage",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10546,
        "name": "delegation.pause",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10526,
        "name": "delegation.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12897,
        "name": "file.attach",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8303,
        "name": "handoff.fail",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8188,
        "name": "handoff.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8276,
        "name": "handoff.state",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12434,
        "name": "image.attach",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12566,
        "name": "image.attach_bytes",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12944,
        "name": "image.detach",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12964,
        "name": "input.detect_drop",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17671,
        "name": "insights.get",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18398,
        "name": "learning.delete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18387,
        "name": "learning.detail",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18409,
        "name": "learning.edit",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18363,
        "name": "learning.frames",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8129,
        "name": "llm.oneshot",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 16712,
        "name": "model.disconnect",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 16609,
        "name": "model.options",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 16632,
        "name": "model.save_key",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15982,
        "name": "paste.collapse",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 12627,
        "name": "pdf.attach",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9106,
        "name": "pet.cancel",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8613,
        "name": "pet.cells",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8958,
        "name": "pet.disable",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8858,
        "name": "pet.export",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8718,
        "name": "pet.gallery",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9151,
        "name": "pet.generate",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9120,
        "name": "pet.generate.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9264,
        "name": "pet.hatch",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8564,
        "name": "pet.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8590,
        "name": "pet.info.meta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8828,
        "name": "pet.remove",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8885,
        "name": "pet.rename",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8972,
        "name": "pet.scale",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8801,
        "name": "pet.select",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8923,
        "name": "pet.thumb",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18078,
        "name": "plugins.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18504,
        "name": "plugins.manage",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13057,
        "name": "preview.restart",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14852,
        "name": "process.kill",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14840,
        "name": "process.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14813,
        "name": "process.stop",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7109,
        "name": "project.facts",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14010,
        "name": "projects.add_folder",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14037,
        "name": "projects.archive",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 13976,
        "name": "projects.create",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14044,
        "name": "projects.delete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14247,
        "name": "projects.discover_repos",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14057,
        "name": "projects.for_cwd",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 13971,
        "name": "projects.get",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 13966,
        "name": "projects.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14500,
        "name": "projects.project_sessions",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14272,
        "name": "projects.record_repos",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14023,
        "name": "projects.remove_folder",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14051,
        "name": "projects.set_active",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 14030,
        "name": "projects.set_primary",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14473,
        "name": "projects.tree",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "projects-wrapper",
        "line": 13995,
        "name": "projects.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13011,
        "name": "prompt.background",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10829,
        "name": "prompt.submit",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 15088,
        "name": "reload.env",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14938,
        "name": "reload.mcp",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17776,
        "name": "rollback.diff",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17699,
        "name": "rollback.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17729,
        "name": "rollback.restore",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13210,
        "name": "secret.respond",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7951,
        "name": "session.activate",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7913,
        "name": "session.active_list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10316,
        "name": "session.branch",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10304,
        "name": "session.close",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10060,
        "name": "session.compress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8351,
        "name": "session.context_breakdown",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 6857,
        "name": "session.create",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7671,
        "name": "session.cwd.set",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7975,
        "name": "session.delete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10008,
        "name": "session.history",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10452,
        "name": "session.interrupt",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7009,
        "name": "session.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7060,
        "name": "session.most_recent",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10778,
        "name": "session.redirect",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7263,
        "name": "session.resume",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10232,
        "name": "session.save",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9932,
        "name": "session.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10745,
        "name": "session.steer",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8025,
        "name": "session.title",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10032,
        "name": "session.undo",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 8327,
        "name": "session.usage",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14715,
        "name": "setup.runtime_check",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14705,
        "name": "setup.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18583,
        "name": "shell.exec",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18420,
        "name": "skills.manage",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18479,
        "name": "skills.reload",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17163,
        "name": "slash.exec",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10670,
        "name": "spawn_tree.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10721,
        "name": "spawn_tree.load",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10627,
        "name": "spawn_tree.save",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10554,
        "name": "subagent.interrupt",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9734,
        "name": "subscription.change",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9709,
        "name": "subscription.preview",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9757,
        "name": "subscription.resume",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9675,
        "name": "subscription.state",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9775,
        "name": "subscription.upgrade",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13205,
        "name": "sudo.respond",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 14788,
        "name": "system.battery",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 13196,
        "name": "terminal.read.respond",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 10817,
        "name": "terminal.resize",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18213,
        "name": "tools.configure",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18139,
        "name": "tools.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18170,
        "name": "tools.show",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 18282,
        "name": "toolsets.list",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 9600,
        "name": "usage.bars",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 7128,
        "name": "verification.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17575,
        "name": "voice.record",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17474,
        "name": "voice.toggle",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "decorator",
        "line": 17652,
        "name": "voice.tts",
        "path": "tui_gateway/server.py"
      }
    ],
    "diff": {
      "additions": [
        "billing.auto_reload",
        "billing.charge",
        "billing.charge_status",
        "billing.state",
        "billing.step_up",
        "command.resolve",
        "complete.slash",
        "config.show",
        "file.attach",
        "handoff.fail",
        "handoff.request",
        "handoff.state",
        "image.attach_bytes",
        "insights.get",
        "llm.oneshot",
        "model.disconnect",
        "pdf.attach",
        "pet.cancel",
        "pet.cells",
        "pet.disable",
        "pet.export",
        "pet.gallery",
        "pet.generate",
        "pet.generate.status",
        "pet.hatch",
        "pet.info",
        "pet.info.meta",
        "pet.remove",
        "pet.rename",
        "pet.scale",
        "pet.select",
        "pet.thumb",
        "plugins.list",
        "plugins.manage",
        "preview.restart",
        "process.kill",
        "process.list",
        "process.stop",
        "project.facts",
        "projects.add_folder",
        "projects.archive",
        "projects.create",
        "projects.delete",
        "projects.discover_repos",
        "projects.for_cwd",
        "projects.get",
        "projects.list",
        "projects.project_sessions",
        "projects.record_repos",
        "projects.remove_folder",
        "projects.set_active",
        "projects.set_primary",
        "projects.tree",
        "projects.update",
        "session.cwd.set",
        "session.most_recent",
        "session.redirect",
        "session.status",
        "setup.runtime_check",
        "setup.status",
        "subscription.change",
        "subscription.preview",
        "subscription.resume",
        "subscription.state",
        "subscription.upgrade",
        "system.battery",
        "terminal.resize",
        "tools.list",
        "tools.show",
        "usage.bars",
        "verification.status",
        "voice.record",
        "voice.toggle",
        "voice.tts"
      ],
      "removals": [],
      "likelyRenames": []
    }
  },
  "events": {
    "names": [
      "agent.terminal.output",
      "approval.request",
      "background.complete",
      "billing.step_up.verification",
      "browser.progress",
      "clarify.expire",
      "clarify.request",
      "error",
      "gateway.ready",
      "message.complete",
      "message.delta",
      "message.interim",
      "message.start",
      "moa.aggregating",
      "moa.phase",
      "moa.progress",
      "moa.reference",
      "notification.clear",
      "notification.show",
      "pane.reveal",
      "pet.generate.progress",
      "pet.hatch.progress",
      "preview.open",
      "preview.restart.complete",
      "preview.restart.progress",
      "reaction",
      "reasoning.available",
      "reasoning.delta",
      "review.summary",
      "secret.expire",
      "secret.request",
      "session.info",
      "session.title",
      "skin.changed",
      "status.update",
      "subagent.complete",
      "subagent.progress",
      "subagent.spawn_requested",
      "subagent.start",
      "subagent.thinking",
      "subagent.tool",
      "sudo.expire",
      "sudo.request",
      "terminal.close",
      "terminal.read.expire",
      "terminal.read.request",
      "thinking.delta",
      "tool.complete",
      "tool.generating",
      "tool.output_risk",
      "tool.start",
      "voice.interrupted",
      "voice.status",
      "voice.transcript"
    ],
    "sources": [
      {
        "kind": "_emit",
        "line": 11629,
        "name": "agent.terminal.output",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1543,
        "name": "approval.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13031,
        "name": "background.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13044,
        "name": "background.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 9910,
        "name": "billing.step_up.verification",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 17941,
        "name": "browser.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "derived-expire",
        "line": 5038,
        "name": "clarify.expire",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_block",
        "line": 5038,
        "name": "clarify.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1975,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4000,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 6758,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 10991,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11786,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12257,
        "name": "error",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "jsonrpc-event-frame",
        "line": 443,
        "name": "gateway.ready",
        "path": "tui_gateway/entry.py"
      },
      {
        "kind": "jsonrpc-event-frame",
        "line": 307,
        "name": "gateway.ready",
        "path": "tui_gateway/ws.py"
      },
      {
        "kind": "_emit",
        "line": 1469,
        "name": "message.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4991,
        "name": "message.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 6835,
        "name": "message.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12083,
        "name": "message.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4968,
        "name": "message.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4973,
        "name": "message.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11880,
        "name": "message.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5070,
        "name": "message.interim",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11889,
        "name": "message.interim",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4959,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 6587,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11383,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11469,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11547,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11703,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12323,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12369,
        "name": "message.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4803,
        "name": "moa.aggregating",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4840,
        "name": "moa.phase",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4813,
        "name": "moa.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4800,
        "name": "moa.reference",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1797,
        "name": "notification.clear",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5035,
        "name": "notification.clear",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1780,
        "name": "notification.show",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5023,
        "name": "notification.show",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "desktop_ui.emit",
        "line": 26,
        "name": "pane.reveal",
        "path": "tools/focus_pane_tool.py"
      },
      {
        "kind": "_emit",
        "line": 9212,
        "name": "pet.generate.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 9228,
        "name": "pet.generate.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 9324,
        "name": "pet.hatch.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "desktop_ui.emit",
        "line": 46,
        "name": "preview.open",
        "path": "tools/open_preview_tool.py"
      },
      {
        "kind": "_emit",
        "line": 13149,
        "name": "preview.restart.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13151,
        "name": "preview.restart.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5457,
        "name": "preview.restart.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13131,
        "name": "preview.restart.progress",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5011,
        "name": "reaction",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4785,
        "name": "reasoning.available",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4962,
        "name": "reasoning.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5012,
        "name": "reasoning.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1942,
        "name": "review.summary",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5948,
        "name": "review.summary",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "derived-expire",
        "line": 5151,
        "name": "secret.expire",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_block",
        "line": 5151,
        "name": "secret.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1476,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1967,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 2279,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 3923,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4551,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5134,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5269,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5520,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5591,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5964,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 7691,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 10184,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 10979,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13388,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13506,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13554,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13568,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 13686,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 15016,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 15939,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 17119,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 17141,
        "name": "session.info",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12198,
        "name": "session.title",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_broadcast_global_event",
        "line": 2903,
        "name": "skin.changed",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_broadcast_global_event",
        "line": 13891,
        "name": "skin.changed",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 1559,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 6582,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11368,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11444,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11530,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 12121,
        "name": "status.update",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1049,
        "name": "subagent.complete",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 2238,
        "name": "subagent.complete",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 2507,
        "name": "subagent.complete",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 2518,
        "name": "subagent.complete",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1140,
        "name": "subagent.progress",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1147,
        "name": "subagent.progress",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1590,
        "name": "subagent.spawn_requested",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1045,
        "name": "subagent.start",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 2114,
        "name": "subagent.start",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1083,
        "name": "subagent.thinking",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "delegate-tool",
        "line": 1136,
        "name": "subagent.tool",
        "path": "tools/delegate_tool.py"
      },
      {
        "kind": "derived-expire",
        "line": 5144,
        "name": "sudo.expire",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_block",
        "line": 5144,
        "name": "sudo.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 11639,
        "name": "terminal.close",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "derived-expire",
        "line": 5055,
        "name": "terminal.read.expire",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_block",
        "line": 5055,
        "name": "terminal.read.request",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5008,
        "name": "thinking.delta",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4750,
        "name": "tool.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4976,
        "name": "tool.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4989,
        "name": "tool.complete",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 5007,
        "name": "tool.generating",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4779,
        "name": "tool.output_risk",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4703,
        "name": "tool.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_emit",
        "line": 4986,
        "name": "tool.start",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_voice_emit",
        "line": 17426,
        "name": "voice.interrupted",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_voice_emit",
        "line": 17623,
        "name": "voice.status",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_voice_emit",
        "line": 17439,
        "name": "voice.transcript",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_voice_emit",
        "line": 17622,
        "name": "voice.transcript",
        "path": "tui_gateway/server.py"
      },
      {
        "kind": "_voice_emit",
        "line": 17624,
        "name": "voice.transcript",
        "path": "tui_gateway/server.py"
      }
    ],
    "coveredDynamicSources": [
      {
        "call": "_emit",
        "line": 4903,
        "path": "tui_gateway/server.py",
        "rule": "delegate-subagent-relay"
      },
      {
        "call": "_emit",
        "line": 11665,
        "path": "tui_gateway/server.py",
        "rule": "delegate-subagent-relay"
      }
    ],
    "diff": {
      "additions": [
        "clarify.expire",
        "pane.reveal",
        "preview.open",
        "secret.expire",
        "subagent.spawn_requested",
        "sudo.expire",
        "terminal.read.expire"
      ],
      "removals": [
        "btw.complete",
        "gateway.protocol_error",
        "gateway.start_timeout",
        "gateway.stderr",
        "tool.progress"
      ],
      "likelyRenames": []
    }
  }
} as const

export const GATEWAY_RPC_METHODS = GATEWAY_INVENTORY.rpc.methods
export const GATEWAY_EVENT_NAMES = GATEWAY_INVENTORY.events.names
export const GATEWAY_INVENTORY_DIFF = { rpc: GATEWAY_INVENTORY.rpc.diff, events: GATEWAY_INVENTORY.events.diff }
