import type { ProducerId } from "./capabilityInventory"

export type CapabilityClassification =
  | "covered.rpc"
  | "covered.slash_gateway"
  | "covered.local"
  | "covered.plugin_api"
  | "unsupported.intentional"
  | "not_applicable.web_only"
  | "not_applicable.internal"
  | "missing"

export type CapabilityPolicy = {
  classification: CapabilityClassification
  rationale: string
  surface?: string
}

export const CAPABILITY_COVERAGE = {
  "rpc:agents.list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:approval.respond": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:billing.auto_reload": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:billing.charge": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:billing.charge_status": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:billing.state": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:billing.step_up": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:browser.manage": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:clarify.respond": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:cli.exec": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:clipboard.paste": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:command.dispatch": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:command.resolve": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:commands.catalog": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:complete.path": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:complete.slash": {"classification": "missing","rationale": "Known producer capability has no first-party Herm surface yet; keep the explicit gap visible until product design assigns ownership."},
  "rpc:config.get": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:config.set": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:config.show": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:credits.view": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:cron.manage": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:delegation.pause": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:delegation.status": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:file.attach": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:handoff.fail": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:handoff.request": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:handoff.state": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:image.attach": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:image.attach_bytes": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:image.detach": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:input.detect_drop": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:insights.get": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:learning.delete": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:learning.detail": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:learning.edit": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:learning.frames": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:llm.oneshot": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:model.disconnect": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:model.options": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:model.save_key": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:paste.collapse": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:pdf.attach": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.cancel": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.cells": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.disable": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.export": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.gallery": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.generate": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.generate.status": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.hatch": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.info": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.info.meta": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.remove": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.rename": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.scale": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.select": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:pet.thumb": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:plugins.list": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:plugins.manage": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:preview.restart": {"classification": "missing","rationale": "Known producer capability has no first-party Herm surface yet; keep the explicit gap visible until product design assigns ownership."},
  "rpc:process.kill": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:process.list": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:process.stop": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:project.facts": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:projects.add_folder": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.archive": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.create": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.delete": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.discover_repos": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.for_cwd": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.get": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.list": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.project_sessions": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.record_repos": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.remove_folder": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.set_active": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.set_primary": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.tree": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:projects.update": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:prompt.background": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:prompt.submit": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:reload.env": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:reload.mcp": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:rollback.diff": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:rollback.list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:rollback.restore": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:secret.respond": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.activate": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.active_list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.branch": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.close": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.compress": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.context_breakdown": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.create": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.cwd.set": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:session.delete": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.history": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.interrupt": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.most_recent": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:session.resume": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.save": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.status": {"classification": "missing","rationale": "Known producer capability has no first-party Herm surface yet; keep the explicit gap visible until product design assigns ownership."},
  "rpc:session.steer": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.title": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.undo": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:session.usage": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:setup.runtime_check": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:setup.status": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:shell.exec": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:skills.manage": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:skills.reload": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:slash.exec": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:spawn_tree.list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:spawn_tree.load": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:spawn_tree.save": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:subagent.interrupt": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:sudo.respond": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:terminal.read.respond": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:terminal.resize": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:tools.configure": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:tools.list": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:tools.show": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:toolsets.list": {"classification": "covered.rpc","rationale": "Herm calls this JSON-RPC method from first-party UI or service code; coverage is structured gateway use, not slash-name inference.","surface": "structured gateway RPC"},
  "rpc:verification.status": {"classification": "not_applicable.internal","rationale": "Gateway lifecycle, harness, process, or diagnostic plumbing rather than a user-facing Herm capability.","surface": "internal gateway contract"},
  "rpc:voice.record": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:voice.toggle": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "rpc:voice.tts": {"classification": "missing","rationale": "Upstream exposes this TUI-gateway RPC, but Herm has no reviewed first-party UI or local command for it yet."},
  "slash-dynamic:quick_commands": {"classification": "covered.slash_gateway","rationale": "commands.catalog discovers this profile-dependent command class at runtime; the committed manifest tracks the deterministic class instead of transient local rows.","surface": "runtime slash catalog"},
  "slash-dynamic:skills": {"classification": "covered.slash_gateway","rationale": "commands.catalog discovers this profile-dependent command class at runtime; the committed manifest tracks the deterministic class instead of transient local rows.","surface": "runtime slash catalog"},
  "slash-extra:compact": {"classification": "covered.local","rationale": "commands.catalog adds this TUI-only pair, and Herm handles the equivalent command as local terminal UI behavior.","surface": "local slash handler"},
  "slash-extra:logs": {"classification": "covered.local","rationale": "commands.catalog adds this TUI-only pair, and Herm handles the equivalent command as local terminal UI behavior.","surface": "local slash handler"},
  "slash-extra:mouse": {"classification": "covered.local","rationale": "commands.catalog adds this TUI-only pair, and Herm handles the equivalent command as local terminal UI behavior.","surface": "local slash handler"},
  "slash-extra:sessions": {"classification": "covered.local","rationale": "commands.catalog adds this TUI-only pair, and Herm handles the equivalent command as local terminal UI behavior.","surface": "local slash handler"},
  "slash:agents": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:approve": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:background": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:billing": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:blueprint": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:branch": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:browser": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:bundles": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:busy": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:clear": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:codex-runtime": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:commands": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:compress": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:config": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:copy": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:credits": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:cron": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:curator": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:debug": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:deny": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:fast": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:footer": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:goal": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:handoff": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:hatch": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:help": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:history": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:image": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:indicator": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:insights": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:journey": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:kanban": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:learn": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:memory": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:moa": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:model": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:new": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:paste": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:personality": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:pet": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:platform": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:platforms": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:plugins": {"classification": "unsupported.intentional","rationale": "Producer marks /plugins as cliOnly, Herm has no TAB_SLASH/local route for it, and the structured plugin RPCs remain separately classified as missing."},
  "slash:profile": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:prompt": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:queue": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:quit": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:reasoning": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:redraw": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:reload": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:reload-mcp": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:reload-skills": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:restart": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:resume": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:retry": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:rollback": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:save": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:sessions": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:sethome": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:skills": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:skin": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:snapshot": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:start": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:status": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:statusbar": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:steer": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:stop": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:subgoal": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:suggestions": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:timestamps": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:title": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:tools": {"classification": "unsupported.intentional","rationale": "Producer command is CLI-only or interactive terminal ownership that Herm deliberately does not forward as a normal slash action."},
  "slash:toolsets": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:topic": {"classification": "not_applicable.internal","rationale": "Producer command is for gateway/messaging control or platform callbacks, not a Herm TUI user capability.","surface": "gateway/messaging control"},
  "slash:undo": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:update": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:usage": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:verbose": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:version": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:voice": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
  "slash:whoami": {"classification": "covered.slash_gateway","rationale": "Herm receives this command from commands.catalog and can dispatch it through slash.exec or command.dispatch when a session is connected.","surface": "gateway slash fallback"},
  "slash:yolo": {"classification": "covered.local","rationale": "Herm handles this slash command in-process or as tab navigation, so support does not depend on slash.exec.","surface": "local slash handler"},
} as const satisfies Record<ProducerId, CapabilityPolicy>

export const CAPABILITY_CLASSIFICATIONS = [
  "covered.rpc",
  "covered.slash_gateway",
  "covered.local",
  "covered.plugin_api",
  "unsupported.intentional",
  "not_applicable.web_only",
  "not_applicable.internal",
  "missing",
] as const
